// The mozjpeg encoder JS is generated by Emscripten and has no first-party
// types. The surface we use is tiny and stable, so a local ambient
// declaration is enough. Keep this file in sync with `loadMozjpeg()`'s
// real usage.
declare const mozjpegFactory: (
  opts: {
    noInitialRun?: boolean;
    locateFile?: (path: string) => string;
    [key: string]: unknown;
  }
) => Promise<{
  encode(
    data: Uint8ClampedArray,
    width: number,
    height: number,
    options: Record<string, unknown>
  ): Uint8Array;
}>;
export default mozjpegFactory;
